/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as VanillaCanvasImport } from './routes/vanillaCanvas'
import { Route as FabricImport } from './routes/fabric'
import { Route as ColorPickersImport } from './routes/colorPickers'
import { Route as GsapImport } from './routes/Gsap'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const VanillaCanvasRoute = VanillaCanvasImport.update({
  id: '/vanillaCanvas',
  path: '/vanillaCanvas',
  getParentRoute: () => rootRoute,
} as any)

const FabricRoute = FabricImport.update({
  id: '/fabric',
  path: '/fabric',
  getParentRoute: () => rootRoute,
} as any)

const ColorPickersRoute = ColorPickersImport.update({
  id: '/colorPickers',
  path: '/colorPickers',
  getParentRoute: () => rootRoute,
} as any)

const GsapRoute = GsapImport.update({
  id: '/Gsap',
  path: '/Gsap',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/Gsap': {
      id: '/Gsap'
      path: '/Gsap'
      fullPath: '/Gsap'
      preLoaderRoute: typeof GsapImport
      parentRoute: typeof rootRoute
    }
    '/colorPickers': {
      id: '/colorPickers'
      path: '/colorPickers'
      fullPath: '/colorPickers'
      preLoaderRoute: typeof ColorPickersImport
      parentRoute: typeof rootRoute
    }
    '/fabric': {
      id: '/fabric'
      path: '/fabric'
      fullPath: '/fabric'
      preLoaderRoute: typeof FabricImport
      parentRoute: typeof rootRoute
    }
    '/vanillaCanvas': {
      id: '/vanillaCanvas'
      path: '/vanillaCanvas'
      fullPath: '/vanillaCanvas'
      preLoaderRoute: typeof VanillaCanvasImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/Gsap': typeof GsapRoute
  '/colorPickers': typeof ColorPickersRoute
  '/fabric': typeof FabricRoute
  '/vanillaCanvas': typeof VanillaCanvasRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/Gsap': typeof GsapRoute
  '/colorPickers': typeof ColorPickersRoute
  '/fabric': typeof FabricRoute
  '/vanillaCanvas': typeof VanillaCanvasRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/Gsap': typeof GsapRoute
  '/colorPickers': typeof ColorPickersRoute
  '/fabric': typeof FabricRoute
  '/vanillaCanvas': typeof VanillaCanvasRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/Gsap' | '/colorPickers' | '/fabric' | '/vanillaCanvas'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/Gsap' | '/colorPickers' | '/fabric' | '/vanillaCanvas'
  id:
    | '__root__'
    | '/'
    | '/Gsap'
    | '/colorPickers'
    | '/fabric'
    | '/vanillaCanvas'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GsapRoute: typeof GsapRoute
  ColorPickersRoute: typeof ColorPickersRoute
  FabricRoute: typeof FabricRoute
  VanillaCanvasRoute: typeof VanillaCanvasRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GsapRoute: GsapRoute,
  ColorPickersRoute: ColorPickersRoute,
  FabricRoute: FabricRoute,
  VanillaCanvasRoute: VanillaCanvasRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/Gsap",
        "/colorPickers",
        "/fabric",
        "/vanillaCanvas"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/Gsap": {
      "filePath": "Gsap.tsx"
    },
    "/colorPickers": {
      "filePath": "colorPickers.tsx"
    },
    "/fabric": {
      "filePath": "fabric.tsx"
    },
    "/vanillaCanvas": {
      "filePath": "vanillaCanvas.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
